Electron_pt:
  x_bins: "20|25:100"
  x_title: "e p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

Muon_pt:
  x_bins: "20|25:100"
  x_title: "#mu p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

Tau_pt:
  x_bins: "10|20:100"
  x_title: "#tau_{h}^{1} p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

pt_sum_tem:
  x_bins: "10|60:300"
  x_title: "#Sigma_{i}^{#tau_{h} e #mu} p_{T}^{i} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False