Muon_pt:
  x_bins: "20|25:100"
  x_title: "#mu p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

Tau1_pt:
  x_bins: "10|20:100"
  x_title: "#tau_{h}^{1} p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

Tau2_pt:
  x_bins: "10|20:100"
  x_title: "#tau_{h}^{2} p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

pt_sum_ttm:
  x_bins: "10|60:300"
  x_title: "#Sigma_{i}^{#tau_{h} #tau_{h} #mu} p_{T}^{i} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

mT_tautau:
  x_bins: "10|0:150"
  x_title: "m^{T}_{#tau_{h} #tau_{h}} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

dr_mutau:
  x_bins: "10|0:5"
  x_title: "#Delta R_{#mu #tau_{h}} (rad)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

mT_total_tautau:
  x_bins: "20|0:300"
  x_title: "m^{T}_{#tau_{h} #tau_{h}} Total (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False