Tau_pt:
  x_bins: "10|20:100"
  x_title: "#tau_{h}^{1} p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

Electron1_pt:
  x_bins: "20|25:100"
  x_title: "e^{1} p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

Electron2_pt:
  x_bins: "10|20:100"
  x_title: "e^{2} p_{T} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

pt_sum_tee:
  x_bins: "10|60:300"
  x_title: "#Sigma_{i}^{#tau_{h} e e} p_{T}^{i} (GeV)"
  y_title: "Events"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False