- name: HNL
  title: "HNL #rightarrow 3l m_{HNL} = 300 GeV (x 10)"
  type: signal
  color: kBlack
  scale: 10.
  files:
  - HNL_tau_M-300_anatuple.root
- name: data
  title: "Data"
  type: data
  files:
  - EGamma_2018_anatuple.root
- name: ExtrapolatedBackground
  title: "Background (extrapolated)"
  type: background
  color: kCyan-3
