- name: HNL
  title: "HNL #rightarrow 3l m_{HNL} = 300 GeV (x 0.5)"
  type: signal
  color: kBlack
  scale: 0.5
  files:
  - HNL_tau_M-300_anatuple.root
- name: data
  title: "Data"
  type: data
  files:
  - EGamma_2018_anatuple.root
  #- Tau_2018_anatuple.root